/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devices */
        get: operations["devices_api_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transport/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transport */
        post: operations["transport_api_transport__action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seek */
        post: operations["seek_api_seek_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip */
        post: operations["skip_api_skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Volume */
        post: operations["volume_api_volume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mute */
        post: operations["mute_api_mute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zone/power": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Zone Power */
        post: operations["zone_power_api_zone_power_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Group */
        post: operations["group_api_group_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group/{side_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Ungroup */
        delete: operations["ungroup_api_group__side_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/art/{cache_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Art
         * @description Serve a cached variant.
         *
         *     404 for an unknown key. Upstream failure (or a disabled proxy) returns **200** with a
         *     neutral placeholder PNG and ``X-Art-Fallback`` so an ``<img>`` never breaks.
         */
        get: operations["art_api_art__cache_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/tidal/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tidal Link Start */
        post: operations["tidal_link_start_api_auth_tidal_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/tidal/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tidal Link Status */
        get: operations["tidal_link_status_api_auth_tidal_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/tidal/unlink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tidal Unlink */
        post: operations["tidal_unlink_api_auth_tidal_unlink_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/tidal/favorites/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tidal Favorite Albums */
        get: operations["tidal_favorite_albums_api_browse_tidal_favorites_albums_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/tidal/favorites/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tidal Favorite Playlists */
        get: operations["tidal_favorite_playlists_api_browse_tidal_favorites_playlists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/tidal/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tidal User Playlists */
        get: operations["tidal_user_playlists_api_browse_tidal_playlists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/tidal/album/{album_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tidal Album */
        get: operations["tidal_album_api_browse_tidal_album__album_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/tidal/playlist/{playlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tidal Playlist */
        get: operations["tidal_playlist_api_browse_tidal_playlist__playlist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browse/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Browse Refresh */
        post: operations["browse_refresh_api_browse_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Play Content */
        post: operations["play_content_api_play_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Play */
        post: operations["sync_play_api_sync_play_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Stop */
        post: operations["sync_stop_api_sync_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Retry */
        post: operations["sync_retry_api_sync_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync State */
        get: operations["sync_state_api_sync_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Sessions */
        get: operations["sync_sessions_api_sync_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/sessions/{session_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Report */
        get: operations["sync_report_api_sync_sessions__session_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Config */
        get: operations["sync_config_api_sync_config_get"];
        put?: never;
        /** Sync Config Update */
        post: operations["sync_config_update_api_sync_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home_api_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings View */
        get: operations["settings_view_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hub/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hub Restart */
        post: operations["hub_restart_api_hub_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/fake/{scenario}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fake Scenario */
        post: operations["fake_scenario_api_dev_fake__scenario__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountStatus */
        AccountStatus: {
            /** Service */
            service: string;
            /** Linked */
            linked: boolean;
            /**
             * State
             * @default unlinked
             * @enum {string}
             */
            state: "linked" | "unlinked" | "pending" | "restoring";
            /** Account Name */
            account_name?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Pending */
            pending?: {
                [key: string]: unknown;
            } | null;
            /** Last Error */
            last_error?: string | null;
        };
        /** Ack */
        Ack: {
            /** Correlation Id */
            correlation_id: string;
            /** Ok */
            ok: boolean;
            /** Action */
            action: string;
            /** Target */
            target?: string | null;
            /** State Version */
            state_version: number;
            error?: components["schemas"]["ErrorEnvelope"] | null;
            /** Partial */
            partial?: components["schemas"]["PartialFailure"][];
            /**
             * Applied
             * @description targets (side or player ids) the command reached
             */
            applied?: string[];
            /**
             * Session Id
             * @description Sync Play session id (sync_* acks)
             */
            session_id?: string | null;
            /**
             * Resolved
             * @description transport acks: side id -> the action actually sent (toggle resolved)
             */
            resolved?: {
                [key: string]: string;
            };
        };
        /**
         * ArtRef
         * @description Artwork as served by the hub art proxy (design system §2.2, §11).
         *
         *     ``url`` is hub-relative (``/api/art/{cache_key}``); append ``?size=96|320|1080|backdrop``.
         *     ``accent`` is the clamped art-derived colour, ``None`` until the proxy has analysed the image.
         *     ``accent_is_safe`` is the hub-side contrast check; when false the client uses ``bg-raised``.
         */
        ArtRef: {
            /** Url */
            url?: string | null;
            /** Accent */
            accent?: string | null;
            /**
             * Accent Is Safe
             * @default false
             */
            accent_is_safe: boolean;
            /** Cache Key */
            cache_key?: string | null;
        };
        /**
         * Availability
         * @description Which ecosystems can play a service's content (the service is linked on that side).
         */
        Availability: {
            /**
             * Heos
             * @default false
             */
            heos: boolean;
            /**
             * Sonos
             * @default false
             */
            sonos: boolean;
        };
        /** BrowseItem */
        BrowseItem: {
            content_ref: components["schemas"]["ContentRef"];
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            art?: components["schemas"]["ArtRef"];
            /** Duration Ms */
            duration_ms?: number | null;
            /** Track Count */
            track_count?: number | null;
            availability?: components["schemas"]["Availability"];
            /** Index */
            index?: number | null;
            /** Album Id */
            album_id?: string | null;
            /** Artist */
            artist?: string | null;
            /** Album */
            album?: string | null;
        };
        /** BrowsePage */
        BrowsePage: {
            /** Items */
            items: components["schemas"]["BrowseItem"][];
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /** Total */
            total?: number | null;
            /** Next Offset */
            next_offset?: number | null;
        };
        /**
         * Capabilities
         * @description What a player or side can do, so Phase 1 does not hard-code vendor checks.
         *
         *     ``supports_next`` / ``supports_prev`` follow the current source (HEOS ``supported_controls``,
         *     Sonos DIDL item class): a radio station has no next track.
         */
        Capabilities: {
            /**
             * Supports Seek
             * @default true
             */
            supports_seek: boolean;
            /**
             * Supports Power
             * @default false
             */
            supports_power: boolean;
            /**
             * Can Group
             * @default true
             */
            can_group: boolean;
            /**
             * Supports Next
             * @default true
             */
            supports_next: boolean;
            /**
             * Supports Prev
             * @default true
             */
            supports_prev: boolean;
        };
        /** ConnectionStatus */
        ConnectionStatus: {
            /**
             * State
             * @default disconnected
             * @enum {string}
             */
            state: "connected" | "reconnecting" | "disconnected" | "disabled";
            /** Last Error */
            last_error?: string | null;
            /**
             * Since
             * Format: date-time
             */
            since?: string;
        };
        /**
         * Container
         * @description An album or playlist with its tracks.
         */
        Container: {
            item: components["schemas"]["BrowseItem"];
            /** Tracks */
            tracks: components["schemas"]["BrowseItem"][];
        };
        /**
         * ContentRef
         * @description Canonical service id: what the hub browses by and plays from ("browse once, play
         *     anywhere", PRD review §2.1). Also the cross-vendor identity of the current track.
         */
        ContentRef: {
            /**
             * Service
             * @enum {string}
             */
            service: "tidal" | "ytmusic" | "pandora";
            /**
             * Kind
             * @enum {string}
             */
            kind: "album" | "playlist" | "track" | "station";
            /** Id */
            id: string;
        };
        /** DevicesResponse */
        DevicesResponse: {
            /** Players */
            players: components["schemas"]["Player"][];
            /** Zones */
            zones: components["schemas"]["Zone"][];
            /** Sides */
            sides: components["schemas"]["Side"][];
            /** Discovered */
            discovered: {
                [key: string]: unknown;
            }[];
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /**
             * Code
             * @enum {string}
             */
            code: "unknown_target" | "unsupported_action" | "not_seekable" | "adapter_disconnected" | "device_offline" | "invalid_argument" | "vendor_error" | "needs_link" | "not_available_on_side" | "unsupported_content" | "sync_mismatch" | "sync_idle" | "sync_stopped";
            /** Message */
            message: string;
            /** Target */
            target?: string | null;
            /** Correlation Id */
            correlation_id: string;
        };
        /** GroupBody */
        GroupBody: {
            /**
             * Vendor
             * @enum {string}
             */
            vendor: "heos" | "sonos";
            /** Coordinator Id */
            coordinator_id: string;
            /** Member Ids */
            member_ids: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardwareItem */
        HardwareItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Vendor */
            vendor: string;
            /**
             * Kind
             * @description player | zone
             */
            kind: string;
            /** Model */
            model?: string | null;
            /** Ip */
            ip?: string | null;
            /**
             * Online
             * @default true
             */
            online: boolean;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description ok or degraded
             */
            status: string;
            /** Degraded */
            degraded: boolean;
            /** Fake Devices */
            fake_devices: boolean;
            /** Version */
            version: string;
            /** Uptime S */
            uptime_s: number;
            /** Connections */
            connections: {
                [key: string]: components["schemas"]["ConnectionStatus"];
            };
            /** Last Error */
            last_error?: string | null;
            /** Discovery Last Run */
            discovery_last_run?: string | null;
            /** State Version */
            state_version: number;
            /**
             * Static
             * @description fonts / app export served
             */
            static?: {
                [key: string]: boolean;
            };
            /**
             * Art Cache
             * @description entries, bytes, hits, misses; null when the proxy is off
             */
            art_cache?: {
                [key: string]: number;
            } | null;
            /**
             * History
             * @description {ok, last_error}
             */
            history?: {
                [key: string]: unknown;
            };
            /**
             * Vault
             * @description {ok, last_error}
             */
            vault?: {
                [key: string]: unknown;
            };
        };
        /** HistoryItem */
        HistoryItem: {
            content_ref: components["schemas"]["ContentRef"];
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            art?: components["schemas"]["ArtRef"];
            /**
             * Last Played At
             * Format: date-time
             */
            last_played_at: string;
            /**
             * Last Targets
             * @description side ids of the last play
             */
            last_targets?: string[];
            /**
             * Play Count
             * @default 1
             */
            play_count: number;
            /**
             * Sync
             * @default false
             */
            sync: boolean;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Items */
            items: components["schemas"]["HistoryItem"][];
        };
        /** HomeResponse */
        HomeResponse: {
            /** Recents */
            recents: components["schemas"]["HistoryItem"][];
            playlists: components["schemas"]["HomeSection"];
            favorite_albums: components["schemas"]["HomeSection"];
            stations: components["schemas"]["HomeSection"];
        };
        /** HomeSection */
        HomeSection: {
            /** Items */
            items?: components["schemas"]["BrowseItem"][];
            /**
             * Needs Link
             * @description service to link, e.g. 'tidal'
             */
            needs_link?: string | null;
            /**
             * Error
             * @description section failed; others still render
             */
            error?: string | null;
        };
        /** HubInfo */
        HubInfo: {
            /** Address */
            address: string;
            /** Port */
            port: number;
            /** Https */
            https: boolean;
            /** Version */
            version: string;
            /** Uptime S */
            uptime_s: number;
            /** Fake Devices */
            fake_devices: boolean;
        };
        /** LinkStartResponse */
        LinkStartResponse: {
            /** Service */
            service: string;
            /** User Code */
            user_code: string;
            /** Verification Url */
            verification_url: string;
            /** Expires In S */
            expires_in_s: number;
            /** Interval S */
            interval_s: number;
        };
        /** MuteBody */
        MuteBody: {
            /**
             * Target
             * @description player id, side id, or 'all'
             */
            target: string;
            /** Muted */
            muted: boolean;
        };
        /** PartialFailure */
        PartialFailure: {
            /** Target */
            target: string;
            /**
             * Code
             * @enum {string}
             */
            code: "unknown_target" | "unsupported_action" | "not_seekable" | "adapter_disconnected" | "device_offline" | "invalid_argument" | "vendor_error" | "needs_link" | "not_available_on_side" | "unsupported_content" | "sync_mismatch" | "sync_idle" | "sync_stopped";
            /** Message */
            message: string;
        };
        /** PlayBody */
        PlayBody: {
            /**
             * Target
             * @description player id, side id, or 'all'
             */
            target: string;
            content_ref: components["schemas"]["ContentRef"];
            /**
             * Start Index
             * @default 0
             */
            start_index: number;
        };
        /** Player */
        Player: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Vendor
             * @enum {string}
             */
            vendor: "heos" | "sonos";
            /** Ip */
            ip?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Online
             * @default true
             */
            online: boolean;
            /**
             * Volume
             * @default 0
             */
            volume: number;
            /**
             * Muted
             * @default false
             */
            muted: boolean;
            /**
             * Play State
             * @default stop
             * @enum {string}
             */
            play_state: "play" | "pause" | "stop" | "unknown";
            /** Group Id */
            group_id?: string | null;
            capabilities?: components["schemas"]["Capabilities"];
        };
        /** RefreshResponse */
        RefreshResponse: {
            /** Cleared */
            cleared: number;
        };
        /** ScenarioResponse */
        ScenarioResponse: {
            /** Scenario */
            scenario: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** State Version */
            state_version: number;
        };
        /** SeekBody */
        SeekBody: {
            /**
             * Target
             * @description player id, side id, or 'all'
             */
            target: string;
            /** Position Ms */
            position_ms: number;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Accounts */
            accounts: components["schemas"]["AccountStatus"][];
            hub: components["schemas"]["HubInfo"];
            /** Hardware */
            hardware: components["schemas"]["HardwareItem"][];
        };
        /** Side */
        Side: {
            /** Id */
            id: string;
            /**
             * Vendor
             * @enum {string}
             */
            vendor: "heos" | "sonos";
            /** Coordinator Player Id */
            coordinator_player_id: string;
            /** Member Ids */
            member_ids: string[];
            /** Name */
            name: string;
            /**
             * Play State
             * @default stop
             * @enum {string}
             */
            play_state: "play" | "pause" | "stop" | "unknown";
            /**
             * Volume
             * @default 0
             */
            volume: number;
            /**
             * Muted
             * @default false
             */
            muted: boolean;
            capabilities?: components["schemas"]["Capabilities"];
        };
        /** SkipBody */
        SkipBody: {
            /**
             * Target
             * @description player id, side id, or 'all'
             */
            target: string;
            /**
             * Delta Ms
             * @description signed; ±15000 for the transport row
             * @default 15000
             */
            delta_ms: number;
        };
        /**
         * SyncConfig
         * @description Hot-reloadable tuning (``POST /api/sync/config``). Defaults come from settings.
         */
        SyncConfig: {
            /**
             * Drift Ms
             * @default 300
             */
            drift_ms: number;
            /**
             * Samples
             * @default 2
             */
            samples: number;
            /**
             * Correction Gap S
             * @default 10
             */
            correction_gap_s: number;
            /**
             * Lookahead Ms
             * @default 400
             */
            lookahead_ms: number;
            /**
             * Monitor S
             * @default 0.5
             */
            monitor_s: number;
            /**
             * Track Grace S
             * @default 3
             */
            track_grace_s: number;
        };
        /** SyncConfigBody */
        SyncConfigBody: {
            /** Drift Ms */
            drift_ms?: number | null;
            /** Samples */
            samples?: number | null;
            /** Correction Gap S */
            correction_gap_s?: number | null;
            /** Lookahead Ms */
            lookahead_ms?: number | null;
            /** Monitor S */
            monitor_s?: number | null;
            /** Track Grace S */
            track_grace_s?: number | null;
        };
        /** SyncPlayBody */
        SyncPlayBody: {
            content_ref: components["schemas"]["ContentRef"];
            /**
             * Heos Target
             * @description HEOS player id, side id, or a list of player ids (grouped first)
             */
            heos_target: string | string[];
            /**
             * Sonos Target
             * @description Sonos player id, side id, or a list of player ids (grouped first)
             */
            sonos_target: string | string[];
            /**
             * Start Index
             * @default 0
             */
            start_index: number;
        };
        /** SyncReport */
        SyncReport: {
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Duration S */
            duration_s: number;
            /** Samples */
            samples: number;
            /** Start Delta Ms */
            start_delta_ms?: number | null;
            /** Drift Mean Ms */
            drift_mean_ms?: number | null;
            /** Drift P95 Ms */
            drift_p95_ms?: number | null;
            /** Drift Max Ms */
            drift_max_ms?: number | null;
            /**
             * Corrections
             * @default 0
             */
            corrections: number;
            /**
             * Reprimes
             * @default 0
             */
            reprimes: number;
            /** Lost Reason */
            lost_reason?: string | null;
        };
        /** SyncSessionSummary */
        SyncSessionSummary: {
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            content_ref: components["schemas"]["ContentRef"];
            /** Title */
            title?: string | null;
            /** Master Side */
            master_side: string;
            /** Follower Side */
            follower_side: string;
            /** Status */
            status: string;
        };
        /** SyncSessionsResponse */
        SyncSessionsResponse: {
            /** Sessions */
            sessions: components["schemas"]["SyncSessionSummary"][];
        };
        /**
         * SyncState
         * @description Sync Play session as streamed to clients (docs/api.md → Sync Play, docs/sync-engine.md).
         *
         *     ``master_side`` is always the HEOS side (it cannot be seeked, so it is the clock);
         *     ``follower_side`` the Sonos side. ``drift_ms`` is follower minus master.
         */
        SyncState: {
            /**
             * Status
             * @default idle
             * @enum {string}
             */
            status: "idle" | "resolving" | "priming" | "verifying" | "starting" | "locked" | "drifting" | "correcting" | "lost" | "stopped";
            /** Session Id */
            session_id?: string | null;
            /** Master Side */
            master_side?: string | null;
            /** Follower Side */
            follower_side?: string | null;
            content_ref?: components["schemas"]["ContentRef"] | null;
            /** Title */
            title?: string | null;
            /** Drift Ms */
            drift_ms?: number | null;
            /** Start Delta Ms */
            start_delta_ms?: number | null;
            /** Last Correction At */
            last_correction_at?: string | null;
            /**
             * Corrections
             * @default 0
             */
            corrections: number;
            /** Reason */
            reason?: string | null;
            /** Started At */
            started_at?: string | null;
        };
        /** TargetBody */
        TargetBody: {
            /**
             * Target
             * @description player id, side id, or 'all'
             */
            target: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumeBody */
        VolumeBody: {
            /** Target */
            target?: string | null;
            /** Level */
            level?: number | null;
            /**
             * Linked
             * @default false
             */
            linked: boolean;
            /** Delta */
            delta?: number | null;
        };
        /**
         * Zone
         * @description A Denon amplifier zone, namespaced by receiver host: ``denon-{host}:{key}``.
         */
        Zone: {
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /**
             * Power
             * @default false
             */
            power: boolean;
            /**
             * Online
             * @default true
             */
            online: boolean;
            /** Host */
            host?: string | null;
            /** Device Id */
            device_id?: string | null;
            /** Player Ids */
            player_ids?: string[];
        };
        /** ZonePowerBody */
        ZonePowerBody: {
            /**
             * Zone Id
             * @description Denon zone id, or a Sonos player/side id for stop+ungroup
             */
            zone_id: string;
            /** On */
            on: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    devices_api_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicesResponse"];
                };
            };
        };
    };
    transport_api_transport__action__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action: "play" | "pause" | "toggle" | "stop" | "next" | "prev";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seek_api_seek_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeekBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_api_skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volume_api_volume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VolumeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mute_api_mute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MuteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    zone_power_api_zone_power_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZonePowerBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    group_api_group_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ungroup_api_group__side_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                side_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    art_api_art__cache_key__get: {
        parameters: {
            query?: {
                size?: string;
            };
            header?: never;
            path: {
                cache_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tidal_link_start_api_auth_tidal_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkStartResponse"];
                };
            };
        };
    };
    tidal_link_status_api_auth_tidal_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountStatus"];
                };
            };
        };
    };
    tidal_unlink_api_auth_tidal_unlink_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountStatus"];
                };
            };
        };
    };
    tidal_favorite_albums_api_browse_tidal_favorites_albums_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowsePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tidal_favorite_playlists_api_browse_tidal_favorites_playlists_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowsePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tidal_user_playlists_api_browse_tidal_playlists_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowsePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tidal_album_api_browse_tidal_album__album_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Container"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tidal_playlist_api_browse_tidal_playlist__playlist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Container"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_refresh_api_browse_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    play_content_api_play_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_play_api_sync_play_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPlayBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_stop_api_sync_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
        };
    };
    sync_retry_api_sync_retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
        };
    };
    sync_state_api_sync_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncState"];
                };
            };
        };
    };
    sync_sessions_api_sync_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncSessionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_report_api_sync_sessions__session_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_config_api_sync_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncConfig"];
                };
            };
        };
    };
    sync_config_update_api_sync_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncConfigBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_api_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeResponse"];
                };
            };
        };
    };
    settings_view_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    hub_restart_api_hub_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    fake_scenario_api_dev_fake__scenario__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
