/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devices */
        get: operations["devices_api_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transport/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transport */
        post: operations["transport_api_transport__action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seek */
        post: operations["seek_api_seek_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip */
        post: operations["skip_api_skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Volume */
        post: operations["volume_api_volume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mute */
        post: operations["mute_api_mute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zone/power": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Zone Power */
        post: operations["zone_power_api_zone_power_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Group */
        post: operations["group_api_group_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group/{side_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Ungroup */
        delete: operations["ungroup_api_group__side_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/fake/{scenario}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fake Scenario */
        post: operations["fake_scenario_api_dev_fake__scenario__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Ack */
        Ack: {
            /** Correlation Id */
            correlation_id: string;
            /** Ok */
            ok: boolean;
            /** Action */
            action: string;
            /** Target */
            target?: string | null;
            /** State Version */
            state_version: number;
            error?: components["schemas"]["ErrorEnvelope"] | null;
            /** Partial */
            partial?: components["schemas"]["PartialFailure"][];
        };
        /**
         * Capabilities
         * @description What a player or side can do, so Phase 1 does not hard-code vendor checks.
         *
         *     ``supports_next`` / ``supports_prev`` follow the current source (HEOS ``supported_controls``,
         *     Sonos DIDL item class): a radio station has no next track.
         */
        Capabilities: {
            /**
             * Supports Seek
             * @default true
             */
            supports_seek: boolean;
            /**
             * Supports Power
             * @default false
             */
            supports_power: boolean;
            /**
             * Can Group
             * @default true
             */
            can_group: boolean;
            /**
             * Supports Next
             * @default true
             */
            supports_next: boolean;
            /**
             * Supports Prev
             * @default true
             */
            supports_prev: boolean;
        };
        /** ConnectionStatus */
        ConnectionStatus: {
            /**
             * State
             * @default disconnected
             * @enum {string}
             */
            state: "connected" | "reconnecting" | "disconnected" | "disabled";
            /** Last Error */
            last_error?: string | null;
            /**
             * Since
             * Format: date-time
             */
            since?: string;
        };
        /** DevicesResponse */
        DevicesResponse: {
            /** Players */
            players: components["schemas"]["Player"][];
            /** Zones */
            zones: components["schemas"]["Zone"][];
            /** Sides */
            sides: components["schemas"]["Side"][];
            /** Discovered */
            discovered: {
                [key: string]: unknown;
            }[];
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /**
             * Code
             * @enum {string}
             */
            code: "unknown_target" | "unsupported_action" | "not_seekable" | "adapter_disconnected" | "device_offline" | "invalid_argument" | "vendor_error";
            /** Message */
            message: string;
            /** Target */
            target?: string | null;
            /** Correlation Id */
            correlation_id: string;
        };
        /** GroupBody */
        GroupBody: {
            /**
             * Vendor
             * @enum {string}
             */
            vendor: "heos" | "sonos";
            /** Coordinator Id */
            coordinator_id: string;
            /** Member Ids */
            member_ids: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description ok or degraded
             */
            status: string;
            /** Degraded */
            degraded: boolean;
            /** Fake Devices */
            fake_devices: boolean;
            /** Version */
            version: string;
            /** Uptime S */
            uptime_s: number;
            /** Connections */
            connections: {
                [key: string]: components["schemas"]["ConnectionStatus"];
            };
            /** Last Error */
            last_error?: string | null;
            /** Discovery Last Run */
            discovery_last_run?: string | null;
            /** State Version */
            state_version: number;
        };
        /** MuteBody */
        MuteBody: {
            /**
             * Target
             * @description player id, side id, or 'all'
             */
            target: string;
            /** Muted */
            muted: boolean;
        };
        /** PartialFailure */
        PartialFailure: {
            /** Target */
            target: string;
            /**
             * Code
             * @enum {string}
             */
            code: "unknown_target" | "unsupported_action" | "not_seekable" | "adapter_disconnected" | "device_offline" | "invalid_argument" | "vendor_error";
            /** Message */
            message: string;
        };
        /** Player */
        Player: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Vendor
             * @enum {string}
             */
            vendor: "heos" | "sonos";
            /** Ip */
            ip?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Online
             * @default true
             */
            online: boolean;
            /**
             * Volume
             * @default 0
             */
            volume: number;
            /**
             * Muted
             * @default false
             */
            muted: boolean;
            /**
             * Play State
             * @default stop
             * @enum {string}
             */
            play_state: "play" | "pause" | "stop" | "unknown";
            /** Group Id */
            group_id?: string | null;
            capabilities?: components["schemas"]["Capabilities"];
        };
        /** ScenarioResponse */
        ScenarioResponse: {
            /** Scenario */
            scenario: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** State Version */
            state_version: number;
        };
        /** SeekBody */
        SeekBody: {
            /**
             * Target
             * @description player id, side id, or 'all'
             */
            target: string;
            /** Position Ms */
            position_ms: number;
        };
        /** Side */
        Side: {
            /** Id */
            id: string;
            /**
             * Vendor
             * @enum {string}
             */
            vendor: "heos" | "sonos";
            /** Coordinator Player Id */
            coordinator_player_id: string;
            /** Member Ids */
            member_ids: string[];
            /** Name */
            name: string;
            /**
             * Play State
             * @default stop
             * @enum {string}
             */
            play_state: "play" | "pause" | "stop" | "unknown";
            /**
             * Volume
             * @default 0
             */
            volume: number;
            /**
             * Muted
             * @default false
             */
            muted: boolean;
            capabilities?: components["schemas"]["Capabilities"];
        };
        /** SkipBody */
        SkipBody: {
            /**
             * Target
             * @description player id, side id, or 'all'
             */
            target: string;
            /**
             * Delta Ms
             * @description signed; ±15000 for the transport row
             * @default 15000
             */
            delta_ms: number;
        };
        /** TargetBody */
        TargetBody: {
            /**
             * Target
             * @description player id, side id, or 'all'
             */
            target: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumeBody */
        VolumeBody: {
            /** Target */
            target?: string | null;
            /** Level */
            level?: number | null;
            /**
             * Linked
             * @default false
             */
            linked: boolean;
            /** Delta */
            delta?: number | null;
        };
        /**
         * Zone
         * @description A Denon amplifier zone, namespaced by receiver host: ``denon-{host}:{key}``.
         */
        Zone: {
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /**
             * Power
             * @default false
             */
            power: boolean;
            /**
             * Online
             * @default true
             */
            online: boolean;
            /** Host */
            host?: string | null;
            /** Device Id */
            device_id?: string | null;
            /** Player Ids */
            player_ids?: string[];
        };
        /** ZonePowerBody */
        ZonePowerBody: {
            /**
             * Zone Id
             * @description Denon zone id, or a Sonos player/side id for stop+ungroup
             */
            zone_id: string;
            /** On */
            on: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    devices_api_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicesResponse"];
                };
            };
        };
    };
    transport_api_transport__action__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action: "play" | "pause" | "toggle" | "stop" | "next" | "prev";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seek_api_seek_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeekBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_api_skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volume_api_volume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VolumeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mute_api_mute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MuteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    zone_power_api_zone_power_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZonePowerBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    group_api_group_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ungroup_api_group__side_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                side_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fake_scenario_api_dev_fake__scenario__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
