/**
 * Pandora Sync via the hub Mac's AirPlay bridge (Phase 7, PRD PAN-4, experimental). Pure view
 * logic so the picker, Now Playing, the mini-player and Settings agree.
 *
 * Facts baked in (docs/api.md "AirPlay bridge and Pandora Sync", docs/prd-review.md §5): the hub
 * Mac plays Pandora itself and streams to AirPlay 2 outputs; the hub only manages the routing and
 * never controls that playback, so transport and seek for the bridged rooms are off (their volume
 * still works). The app sends the chosen side ids; the hub matches rooms to outputs. Amber stays
 * reserved for Sync Play, which creates a live audio state the hub drives; this hands off to the
 * Mac, so its affordances are plain text. One name everywhere: "Pandora Sync" (§10).
 */
import messages from "./hub/messages.json";
import type { AirPlayInfo } from "./hub/library";
import type { HubState, PandoraSyncState } from "./hub/types";
import { joinRooms } from "./sync";

/**
 * The hub owns copy where it exports it (`templates.airplay.*` in messages.json, regenerated by
 * `npm run openapi`); the second key is the hub's older spelling; the fallback is the client's.
 */
function hubMessage(keys: string[], fallback: string): string {
  const templates = (messages as { templates?: Record<string, unknown> }).templates ?? {};
  const airplay = templates.airplay && typeof templates.airplay === "object" ? (templates.airplay as Record<string, unknown>) : {};
  for (const k of keys) {
    const v = airplay[k];
    if (typeof v === "string" && v.trim()) return v;
  }
  return fallback;
}

export const PANDORA_SYNC = "Pandora Sync";
export const PANDORA_SYNC_BUTTON = `${PANDORA_SYNC} (experimental)`;
export const PANDORA_SYNC_CHIP = PANDORA_SYNC;
export const PANDORA_SYNC_STOP = "Stop";
export const PANDORA_SYNC_STARTED: string = hubMessage(["pandora_sync_started"], "Pandora opened on the hub Mac. Press play there; the rooms follow.");
export const PANDORA_SYNC_STOPPED: string = hubMessage(["pandora_sync_stopped"], "Pandora Sync ended; the Mac's outputs are back to how they were.");
export const AIRPLAY_NO_MATCH_TEMPLATE: string = hubMessage(["airplay_no_match", "no_match"], "No AirPlay outputs match {rooms}. Pick the outputs by hand.");
export const AIRPLAY_UNAVAILABLE_TEMPLATE: string = hubMessage(["airplay_unavailable", "unavailable"], "AirPlay isn't available on the hub right now: {reason}");
/** Client constant: the hub's refusal message replaces it whenever one arrives. */
export const PANDORA_SYNC_FAILED = "Pandora Sync didn't start.";
/** Full-width caption under the meta while a room is bridged (UX U7). */
export const PANDORA_SYNC_CONTROLLED = "Press play on the hub Mac; the rooms follow. Controls are there while Pandora Sync is on.";
export const AIRPLAY_ROW_TITLE = `${PANDORA_SYNC} (AirPlay bridge)`;
export const AIRPLAY_DISCLOSURE = "Experimental. Pandora Sync points the Mac's AirPlay outputs at your rooms and opens Pandora there; someone presses play on the Mac.";
export const AIRPLAY_OUTPUTS_TITLE = "AirPlay outputs";
export const AIRPLAY_OUTPUTS_NOTE = "Outputs are chosen on the hub Mac. Checked ones are selected there right now.";
const AIRPLAY_NO_REASON = "The Music app didn't answer.";

/** Picker note tied to the button via aria-describedby (UX U1). */
export function pandoraSyncNote(roomNames: readonly string[]): string {
  const rooms = roomNames.length ? joinRooms([...roomNames]) : "your rooms";
  return `The hub Mac plays this station to ${rooms} over AirPlay. It opens Pandora there; press play on the Mac.`;
}

export function isPandoraSyncActive(state: HubState | null | undefined): boolean {
  return !!state?.pandora_sync?.active;
}

export function pandoraSync(state: HubState | null | undefined): PandoraSyncState | null {
  return state?.pandora_sync ?? null;
}

/**
 * Is this room under the bridge right now? Scoped to `side_ids`, so other rooms stay fully live.
 * A hub that reports `active` without `side_ids` (older shape) bridges every room.
 */
export function bridgedSide(sideId: string | null | undefined, ps: PandoraSyncState | null | undefined): boolean {
  if (!ps?.active || !sideId) return false;
  return ps.side_ids.length === 0 || ps.side_ids.includes(sideId);
}

/**
 * Picker rule: the affordance appears only for a Pandora station AND when the hub reports the
 * bridge available, and never while a Sync Play session is live (the hub refuses with
 * `sync_active`; the app hides the button first). Never for other content.
 */
export function pandoraSyncOffered(ref: { service: string; kind: string } | null | undefined, airplay: AirPlayInfo | null | undefined, syncActive = false): boolean {
  return !syncActive && ref?.service === "pandora" && ref.kind === "station" && !!airplay?.available;
}

/** Settings row line: "Available" / "Unavailable · {reason}" / "Off". */
export function airplayRowStatus(info: AirPlayInfo | null | undefined): string {
  if (!info?.enabled) return "Off";
  if (info.available) return "Available";
  return `Unavailable · ${info.reason?.trim() || AIRPLAY_NO_REASON}`;
}

/** Bridged room count for labels: the hub's `side_ids`, else its output names. */
function roomCount(ps: PandoraSyncState): number {
  return ps.side_ids.length || ps.outputs.length;
}

/** Room names for the indicator's accessible label: "Pandora Sync: Kitchen and Living Room Amp". */
export function pandoraSyncLabel(state: HubState | null | undefined, sides?: Record<string, { name: string }>): string | null {
  const ps = pandoraSync(state);
  if (!ps?.active) return null;
  const names = ps.side_ids.length && sides ? ps.side_ids.map((id) => sides[id]?.name ?? "another room") : ps.outputs;
  return names.length ? `${PANDORA_SYNC}: ${joinRooms(names)}` : PANDORA_SYNC;
}

/** Short header form that never wraps: "Pandora Sync · 2 rooms". */
export function pandoraSyncLabelShort(state: HubState | null | undefined): string | null {
  const ps = pandoraSync(state);
  if (!ps?.active) return null;
  const n = roomCount(ps);
  return n > 0 ? `${PANDORA_SYNC} · ${n} ${n === 1 ? "room" : "rooms"}` : PANDORA_SYNC;
}
