/**
 * Service and vendor facts shared by home, settings, the picker and browse detail (PRD §3.7 SET-1,
 * design system §8, §10). Labels, the vendor-app names, the unsupported-on-vendor table and every
 * shared sentence come from the hub's exported `messages.json` (`GET /api/meta/messages`,
 * regenerated by `npm run openapi`), so the app and the hub never disagree on copy; the contract
 * tests read that file too. The hub's per-room ack messages name the room (`{side}`); the picker
 * needs the same fact *before* a tap, on the row that is the room, so the pre-tap forms here take
 * the hub's labels and reason codes and drop the subject. Tidal and YouTube Music are linked through
 * the hub (device-code flow); Pandora is linked inside each vendor's own app and only reported.
 */
import messages from "./hub/messages.json";
import type { Availability, Service } from "./hub/library";

export type Vendor = "heos" | "sonos";
/** Why a vendor cannot play an item, from the hub (`availability.reasons`, `messages.reasons`). */
export type AvailabilityReason = "unsupported" | "not_linked" | "not_in_account" | "auth_fault";

export const SERVICE_LABEL: Record<Service, string> = messages.service_label;
export const VENDOR_LABEL: Record<Vendor, string> = messages.vendor_label;
export const VENDOR_APP: Record<Vendor, string> = messages.vendor_app;
export const PANDORA_CONCURRENT_MSG: string = messages.templates.pandora_concurrent;
export const SYNC_UNSUPPORTED_MSG: string = messages.templates.sync_unsupported_content;

/** Services with a hub sign-in flow (`/api/auth/{service}/…`); their rows in Settings are live. */
export const HUB_LINKED_SERVICES: readonly Service[] = ["tidal", "ytmusic"];

export function isHubLinked(service: string | null | undefined): service is "tidal" | "ytmusic" {
  return !!service && (HUB_LINKED_SERVICES as readonly string[]).includes(service);
}

export function isService(x: string | null | undefined): x is Service {
  return x === "tidal" || x === "ytmusic" || x === "pandora";
}

/** The hub's table of services a vendor cannot play at all (`commands.UNSUPPORTED_ON_VENDOR`). */
export function isUnsupportedOn(vendor: Vendor, service: Service): boolean {
  return (messages.unsupported_on_vendor as string[][]).some(([v, s]) => v === vendor && s === service);
}

function fill(template: string, service: Service, vendor: Vendor): string {
  return template.replaceAll("{service}", SERVICE_LABEL[service]).replaceAll("{vendor}", VENDOR_LABEL[vendor]).replaceAll("{vendor_app}", VENDOR_APP[vendor]);
}

/**
 * One sentence for why a vendor cannot play a service (§10, one phrase for one fact), keyed by the
 * hub's reason code: "unsupported" → the hub's own template ("{Service} isn't available on
 * {Vendor}."); "not_linked" → "{Service} is set up in the {Vendor} app."; "not_in_account" → "Not in
 * the {Vendor} {Service} account."; "auth_fault" → "{Vendor} can't reach {Service} right now; sign in
 * again in the {Vendor} app." Null or unknown reads as not linked. Availability itself always comes
 * from the item.
 */
export function serviceUnavailableCopy(service: Service, vendor: Vendor, reason: AvailabilityReason | string | null | undefined): string {
  switch (reason) {
    case "unsupported":
      return fill(messages.templates.not_available.unsupported, service, vendor);
    case "not_in_account":
      return fill("Not in the {vendor} {service} account.", service, vendor);
    case "auth_fault":
      return fill("{vendor} can't reach {service} right now; sign in again in the {vendor_app}.", service, vendor);
    default:
      return fill("{service} is set up in the {vendor_app}.", service, vendor);
  }
}

/**
 * The reason a vendor cannot play an item: the hub's `reasons[vendor]` when present; otherwise the
 * hub's unsupported table, then an unlinked vendor (from the section's link state) reads as not
 * linked, a linked vendor lacking a Pandora station as not in the account, anything else as not
 * linked.
 */
export function reasonFor(availability: Availability | null | undefined, vendor: Vendor, service: Service | undefined, unlinked: readonly Vendor[] = []): AvailabilityReason {
  const r = availability?.reasons?.[vendor];
  if (r) return r;
  if (service && isUnsupportedOn(vendor, service)) return "unsupported";
  if (unlinked.includes(vendor)) return "not_linked";
  return service === "pandora" ? "not_in_account" : "not_linked";
}

/**
 * Neutral one-sided label for an item (design §13 1.3): both vendors → null; one-sided →
 * "Sonos rooms only" / "HEOS rooms only"; neither → "Not available". Used for card subtitles,
 * the detail header caption and per-row notes, so there is exactly one phrasing.
 */
export function roomsOnlyLabel(availability: Availability | null | undefined): string | null {
  if (!availability) return null;
  if (availability.heos && availability.sonos) return null;
  if (availability.heos) return `${VENDOR_LABEL.heos} rooms only`;
  if (availability.sonos) return `${VENDOR_LABEL.sonos} rooms only`;
  return "Not available";
}
